# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0003_auto_20161010_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 14, 6, 57, 196000)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
