# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0004_auto_20161010_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 14, 10, 8, 8000)),
        ),
    ]
