# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0009_auto_20161010_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 14, 21, 15, 961000)),
        ),
    ]
