# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0010_auto_20161010_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 12, 14, 29, 834000)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
