# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0012_auto_20161107_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='national_card_photo',
            field=models.ImageField(null=True, upload_to=b'nationalCardScans/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 13, 45, 57, 208000)),
        ),
    ]
