# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0013_auto_20161107_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 15, 12, 50, 25, 292000)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'nationalCardScans/'),
        ),
    ]
