# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0015_auto_20161122_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 27, 17, 53, 42, 425000)),
        ),
        migrations.AlterField(
            model_name='verificationcodes',
            name='user_code',
            field=models.IntegerField(),
        ),
    ]
