# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0018_auto_20161211_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='when',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='when',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(choices=[(b'Amin', b'Amin Investment Bank'), (b'Day', b'Day Bank'), (b'Ayandeh', b'Ayande Bank')], max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 18, 12, 29, 29, 716000)),
        ),
    ]
