# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0019_auto_20161218_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 19, 12, 48, 55, 607000)),
        ),
    ]
