# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 14:58
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0021_auto_20161219_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 19, 18, 28, 46, 197000)),
        ),
    ]
