# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 10:30
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0022_auto_20161219_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(default=6216922447402432071L, max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 20, 14, 0, 16, 279000)),
        ),
    ]
